### ISSUE TITLE
Error line 1062

### ISSUE THREAD

**Issue by storm5510** [gchilders/msieve_nfsathome#1]
This is with _Ubuntu 20.04_.  When I try to run _msieve_ with certain switches, it will fail and display "error line 1062." I assume this is the specific line in a piece of code. This happens with  most of the "-n" switches, but not all. "-n" will display a message similar to "unable to write or read polynomials."  I do not know if this is related: When _msieve_ starts, the top line will display "SVN unknown." I have had problems with Windows variants which did not have a numeric value there.

Thank you.

**Comment by gchilders** [comment]
You must have the files stage1_core.ptx and lanczos_kernel.ptx in the same directory in which you are running msieve as well as sort_engine.so and spmv_engine.so in the cub subdirectory.
